"use client";

import { useEffect, useState, type ReactNode } from "react";
import { GoogleAuthProvider, onAuthStateChanged, signInWithEmailAndPassword, signInWithPopup, signOut, type User } from "firebase/auth";
import { clientAuth } from "@/lib/firebase-client";
import type { SiteData, Service, Job, Post, Testimonial } from "@/lib/site-data";

type Tab = "Overview" | "Homepage" | "About" | "Pages" | "Services" | "Jobs" | "Testimonials" | "Blog" | "Media" | "Settings" | "Inbox";
const tabs: Tab[] = ["Overview", "Homepage", "About", "Pages", "Services", "Jobs", "Testimonials", "Blog", "Media", "Settings", "Inbox"];
type Media = { id: string; url: string; alt: string };
type Submission = { id: string; firstName: string; lastName: string; email: string; phone: string; createdAt: string | null; status: string; [key: string]: unknown };

function Field({ label, value, onChange, multiline = false }: { label: string; value: string; onChange: (value: string) => void; multiline?: boolean }) {
  return <label className="admin-field"><span>{label}</span>{multiline ? <textarea value={value} rows={4} onChange={(e) => onChange(e.target.value)}/> : <input value={value} onChange={(e) => onChange(e.target.value)}/>}</label>;
}

function Panel({ title, eyebrow, children }: { title: string; eyebrow?: string; children: ReactNode }) {
  return <section className="admin-panel"><div className="admin-panel-head">{eyebrow && <span>{eyebrow}</span>}<h2>{title}</h2></div>{children}</section>;
}

export function AdminApp({ initialSite, configured }: { initialSite: SiteData; configured: boolean }) {
  const [site, setSite] = useState<SiteData>(initialSite);
  const [user, setUser] = useState<User | null>(null);
  const [authReady, setAuthReady] = useState(false);
  const [tab, setTab] = useState<Tab>("Overview");
  const [message, setMessage] = useState("");
  const [busy, setBusy] = useState(false);
  const [email, setEmail] = useState("");
  const [password, setPassword] = useState("");
  const [selectedService, setSelectedService] = useState(0);
  const [selectedJob, setSelectedJob] = useState(0);
  const [selectedPost, setSelectedPost] = useState(0);
  const [selectedTestimonial, setSelectedTestimonial] = useState(0);
  const [media, setMedia] = useState<Media[]>([]);
  const [mediaAlt, setMediaAlt] = useState("");
  const [inquiries, setInquiries] = useState<Submission[]>([]);
  const [applications, setApplications] = useState<Submission[]>([]);

  useEffect(() => {
    const auth = clientAuth();
    if (!configured || !auth) { setAuthReady(true); return; }
    return onAuthStateChanged(auth, async (current) => {
      setUser(current); setAuthReady(true);
      if (!current) return;
      try {
        const token = await current.getIdToken();
        const response = await fetch("/api/admin/site", { headers: { authorization: `Bearer ${token}` } });
        const result = await response.json();
        if (!response.ok) {
          if (response.status === 401 || response.status === 403) await signOut(auth);
          throw new Error(result.error || "Access denied.");
        }
        setSite(result.draft);
        setMessage("");
      } catch (cause) { setMessage(cause instanceof Error ? cause.message : "Could not load the CMS."); }
    });
  }, [configured]);

  async function token() { const value = await user?.getIdToken(); if (!value) throw new Error("Sign in required."); return value; }
  async function loginGoogle() { const auth = clientAuth(); if (!auth) return; setMessage(""); try { await signInWithPopup(auth, new GoogleAuthProvider()); } catch (cause) { setMessage(cause instanceof Error ? cause.message : "Could not sign in."); } }
  async function loginEmail(event: React.FormEvent) { event.preventDefault(); const auth = clientAuth(); if (!auth) return; setMessage(""); try { await signInWithEmailAndPassword(auth, email, password); } catch { setMessage("Sign in failed. Check your account and password."); } }
  async function save(mode: "save" | "publish") {
    setBusy(true); setMessage("");
    try { const bearer = await token(); const response = await fetch("/api/admin/site", { method: "PUT", headers: { "content-type": "application/json", authorization: `Bearer ${bearer}` }, body: JSON.stringify({ content: site, mode }) }); const result = await response.json(); if (!response.ok) throw new Error(result.error || "Could not save."); setMessage(mode === "publish" ? "Published successfully." : "Draft saved."); }
    catch (cause) { setMessage(cause instanceof Error ? cause.message : "Could not save."); }
    finally { setBusy(false); }
  }
  async function loadMedia() { try { const bearer = await token(); const response = await fetch("/api/admin/media", { headers: { authorization: `Bearer ${bearer}` } }); const result = await response.json(); if (!response.ok) throw new Error(result.error); setMedia(result.media); } catch (cause) { setMessage(cause instanceof Error ? cause.message : "Could not load media."); } }
  async function loadInbox() { try { const bearer = await token(); const response = await fetch("/api/admin/submissions", { headers: { authorization: `Bearer ${bearer}` } }); const result = await response.json(); if (!response.ok) throw new Error(result.error); setInquiries(result.inquiries); setApplications(result.applications); } catch (cause) { setMessage(cause instanceof Error ? cause.message : "Could not load inbox."); } }
  async function updateSubmission(kind: "inquiries" | "applications", id: string, status: string) {
    setMessage("");
    try {
      const bearer = await token();
      const response = await fetch("/api/admin/submissions", { method: "PATCH", headers: { "content-type": "application/json", authorization: `Bearer ${bearer}` }, body: JSON.stringify({ kind, id, status }) });
      const result = await response.json();
      if (!response.ok) throw new Error(result.error || "Could not update the submission.");
      const setter = kind === "inquiries" ? setInquiries : setApplications;
      setter((current) => current.map((item) => item.id === id ? { ...item, status } : item));
      setMessage("Submission status updated.");
    } catch (cause) { setMessage(cause instanceof Error ? cause.message : "Could not update the submission."); }
  }
  async function upload(event: React.FormEvent<HTMLFormElement>) { event.preventDefault(); const form = event.currentTarget; const formData = new FormData(form); formData.set("alt", mediaAlt); setBusy(true); setMessage(""); try { const bearer = await token(); const response = await fetch("/api/admin/media", { method: "POST", headers: { authorization: `Bearer ${bearer}` }, body: formData }); const result = await response.json(); if (!response.ok) throw new Error(result.error || "Upload failed."); setMedia((current) => [{ id: result.id, url: result.url, alt: result.alt }, ...current]); setMediaAlt(""); form.reset(); setMessage("Image uploaded. Assign it to a page using the buttons below."); } catch (cause) { setMessage(cause instanceof Error ? cause.message : "Upload failed."); } finally { setBusy(false); } }

  function patchSection<K extends "settings" | "home" | "about" | "pages">(section: K, key: keyof SiteData[K], value: string) { setSite((current) => ({ ...current, [section]: { ...current[section], [key]: value } })); }
  function patchArray<K extends "services" | "jobs" | "posts" | "testimonials">(section: K, index: number, patch: Partial<SiteData[K][number]>) { setSite((current) => ({ ...current, [section]: current[section].map((item, i) => i === index ? { ...item, ...patch } : item) })); }
  function addArray<K extends "services" | "jobs" | "posts" | "testimonials">(section: K, item: SiteData[K][number]) { setSite((current) => ({ ...current, [section]: [...current[section], item] })); }
  function removeArray<K extends "services" | "jobs" | "posts" | "testimonials">(section: K, index: number) { setSite((current) => ({ ...current, [section]: current[section].filter((_, i) => i !== index) })); }
  function changeTab(next: Tab) { setTab(next); setMessage(""); if (next === "Media" && user) void loadMedia(); if (next === "Inbox" && user) void loadInbox(); }

  if (!authReady) return <div className="admin-loading">Loading website editor…</div>;
  if (configured && !user) return <div className="admin-login"><div className="admin-login-card"><img src="/images/logo-transparent.png" alt="Heartstead Home Care"/><h1>Website Admin</h1><p>Sign in with the approved owner account to edit the site.</p><button type="button" onClick={loginGoogle}>Continue with Google</button><div className="admin-separator">or use email and password</div><form onSubmit={loginEmail}><input type="email" value={email} onChange={(e) => setEmail(e.target.value)} placeholder="Email" required/><input type="password" value={password} onChange={(e) => setPassword(e.target.value)} placeholder="Password" required/><button type="submit">Sign In</button></form>{message && <p role="alert" className="admin-error">{message}</p>}</div></div>;
  const previewOnly = !configured;
  const service = site.services[selectedService]; const job = site.jobs[selectedJob]; const post = site.posts[selectedPost]; const testimonial = site.testimonials[selectedTestimonial];
  function submissionCards(kind: "inquiries" | "applications", items: Submission[]) {
    if (!items.length) return <p>No {kind === "inquiries" ? "care inquiries" : "job applications"} are loaded.</p>;
    return items.map((item) => <details className="admin-submission-card" key={item.id}>
      <summary><strong>{item.firstName} {item.lastName}</strong><span>{item.email} · {item.phone}</span><small>{item.createdAt ? new Date(item.createdAt).toLocaleString() : "Date unavailable"} · {item.status.replace("_", " ")}</small></summary>
      <div className="admin-submission-detail">{Object.entries(item).filter(([key]) => !["id", "firstName", "lastName", "email", "phone", "createdAt", "updatedAt", "updatedBy", "status", "website"].includes(key)).map(([key, value]) => <p key={key}><strong>{key.replace(/([A-Z])/g, " $1")}:</strong> {String(value ?? "")}</p>)}<a href={`mailto:${item.email}`}>Reply by email</a><label>Status <select value={item.status} disabled={previewOnly} onChange={(event) => void updateSubmission(kind, item.id, event.target.value)}><option value="new">New</option><option value="in_progress">In progress</option><option value="closed">Closed</option></select></label></div>
    </details>);
  }

  return <div className="admin-shell"><aside className="admin-sidebar"><div className="admin-brand"><img src="/images/logo-transparent.png" alt="Heartstead Home Care"/></div><p>WEBSITE</p><nav aria-label="Admin navigation">{tabs.map((item) => <button key={item} className={tab === item ? "active" : ""} type="button" onClick={() => changeTab(item)}>{item}</button>)}</nav><div className="admin-owner"><strong>{previewOnly ? "Setup preview" : "Owner access"}</strong><small>{user?.email ?? "heartsteadhomecare@gmail.com"}</small>{user && <button type="button" onClick={() => signOut(clientAuth()!)}>Sign out</button>}</div></aside><main className="admin-main"><header className="admin-top"><div><span>Website / {tab}</span><h1>{tab === "Overview" ? "Good afternoon, Heartstead." : tab}</h1><p>{tab === "Overview" ? "Manage the content families see on your website." : "Edit website content before publishing."}</p></div><div className="admin-actions"><a href="/" target="_blank" rel="noopener noreferrer">View Public Site ↗</a><button disabled={previewOnly || busy} type="button" onClick={() => save("save")}>Save Draft</button><button disabled={previewOnly || busy} className="publish" type="button" onClick={() => save("publish")}>Publish</button></div></header>
    {previewOnly && <div className="admin-notice">Design and local content preview. Add Firebase project config and the owner UID to enable authentication, uploads, the inbox, and publishing.</div>}
    {message && <div className="admin-message" role="status">{message}</div>}
    {tab === "Overview" && <><div className="admin-stats"><div><span>Public pages</span><strong>{14 + site.services.length + site.posts.filter((item) => item.published).length}</strong><small>Core, service, and article pages</small></div><div><span>Care services</span><strong>{site.services.length}</strong><small>Editable entries</small></div><div><span>Job listings</span><strong>{site.jobs.filter((item) => item.published).length}</strong><small>Published openings</small></div><div><span>New inquiries</span><strong>{inquiries.length || "—"}</strong><small>Open inbox to refresh</small></div></div><div className="admin-overview-grid"><Panel title="Homepage sections" eyebrow="CONTENT EDITOR">{["Hero message", "Why Heartstead", "Care highlights", "Care team"].map((item) => <button type="button" className="admin-row" onClick={() => changeTab("Homepage")} key={item}>{item}<span>›</span></button>)}</Panel><Panel title="Quick actions" eyebrow="WEBSITE TOOLS"><button type="button" className="admin-row" onClick={() => changeTab("Media")}>Upload and assign a photo<span>›</span></button><button type="button" className="admin-row" onClick={() => changeTab("Services")}>Edit care services<span>›</span></button><button type="button" className="admin-row" onClick={() => changeTab("Jobs")}>Post a caregiver job<span>›</span></button><button type="button" className="admin-row" onClick={() => changeTab("Inbox")}>View inquiries and applications<span>›</span></button></Panel></div></>}
    {tab === "Homepage" && <Panel title="Homepage" eyebrow="EDIT SECTIONS"><p className="admin-help">Edit every headline, introduction, promise, and benefit shown on the homepage.</p><div className="admin-form-grid">{(Object.keys(site.home) as Array<keyof SiteData["home"]>).map((key) => <Field key={key} label={key.replace(/([A-Z])/g, " $1")} value={site.home[key]} onChange={(v) => patchSection("home", key, v)} multiline={key.endsWith("Text")}/>)}</div></Panel>}
    {tab === "About" && <Panel title="About Heartstead" eyebrow="ABOUT PAGE"><div className="admin-form-grid">{(Object.keys(site.about) as Array<keyof SiteData["about"]>).map((key) => <Field key={key} label={key.replace(/([A-Z])/g, " $1")} value={site.about[key]} onChange={(v) => patchSection("about", key, v)} multiline/>)}</div></Panel>}
    {tab === "Pages" && <Panel title="Other pages" eyebrow="PAGE CONTENT"><p className="admin-help">Edit the introductions and approved policy text shown across the website.</p><div className="admin-form-grid">{(Object.keys(site.pages) as Array<keyof SiteData["pages"]>).map((key) => <Field key={key} label={key.replace(/([A-Z])/g, " $1")} value={site.pages[key]} onChange={(v) => patchSection("pages", key, v)} multiline/>)}</div></Panel>}
    {tab === "Settings" && <Panel title="Site settings" eyebrow="GLOBAL CONTENT"><div className="admin-form-grid">{(["brandName", "tagline", "phone", "publicEmail", "address", "serviceArea", "heroImage", "heroImageAlt", "familyImage", "familyImageAlt", "caregiverImage", "caregiverImageAlt"] as const).map((key) => <Field key={key} label={key.replace(/([A-Z])/g, " $1")} value={site.settings[key]} onChange={(v) => patchSection("settings", key, v)}/>)}</div></Panel>}
    {tab === "Services" && <Panel title="Care services" eyebrow="SERVICE CATALOGUE"><div className="admin-split"><div className="admin-list">{site.services.map((item, index) => <button className={selectedService === index ? "selected" : ""} type="button" key={`${item.slug}-${index}`} onClick={() => setSelectedService(index)}>{item.title}</button>)}<button type="button" className="admin-add" onClick={() => { addArray("services", { slug: `new-service-${Date.now()}`, title: "New Service", summary: "Describe this service.", intro: "Describe how this service supports clients.", image: site.settings.familyImage, category: "Everyday support" } as Service); setSelectedService(site.services.length); }}>+ Add service</button></div>{service && <div className="admin-detail"><Field label="Page URL slug" value={service.slug} onChange={(v) => patchArray("services", selectedService, { slug: v })}/><Field label="Service title" value={service.title} onChange={(v) => patchArray("services", selectedService, { title: v })}/><Field label="Card summary" value={service.summary} onChange={(v) => patchArray("services", selectedService, { summary: v })} multiline/><Field label="Page introduction" value={service.intro} onChange={(v) => patchArray("services", selectedService, { intro: v })} multiline/><Field label="Image URL" value={service.image} onChange={(v) => patchArray("services", selectedService, { image: v })}/><label className="admin-field"><span>Category</span><select value={service.category} onChange={(e) => patchArray("services", selectedService, { category: e.target.value as Service["category"] })}>{["Care schedules", "Everyday support", "Specialized care", "Care guides"].map((value) => <option key={value}>{value}</option>)}</select></label><label className="admin-check"><input type="checkbox" checked={Boolean(service.featured)} onChange={(e) => patchArray("services", selectedService, { featured: e.target.checked })}/> Feature on homepage</label><button className="admin-danger" type="button" onClick={() => { removeArray("services", selectedService); setSelectedService(0); }}>Remove service</button></div>}</div></Panel>}
    {tab === "Jobs" && <Panel title="Caregiver jobs" eyebrow="OPEN CASES"><p className="admin-help">Published jobs appear on the Open Cases page. An empty list shows a general application option.</p><div className="admin-split"><div className="admin-list">{site.jobs.map((item, index) => <button className={selectedJob === index ? "selected" : ""} type="button" key={`${item.id}-${index}`} onClick={() => setSelectedJob(index)}>{item.title} {item.published ? "●" : "○"}</button>)}<button type="button" className="admin-add" onClick={() => { addArray("jobs", { id: `job-${Date.now()}`, title: "New Caregiver Position", employmentType: "Part-time", location: site.settings.serviceArea, summary: "Describe the opportunity.", published: false } as Job); setSelectedJob(site.jobs.length); }}>+ Add job</button></div>{job && <div className="admin-detail"><Field label="Title" value={job.title} onChange={(v) => patchArray("jobs", selectedJob, { title: v })}/><Field label="Employment type" value={job.employmentType} onChange={(v) => patchArray("jobs", selectedJob, { employmentType: v })}/><Field label="Location" value={job.location} onChange={(v) => patchArray("jobs", selectedJob, { location: v })}/><Field label="Description" value={job.summary} onChange={(v) => patchArray("jobs", selectedJob, { summary: v })} multiline/><label className="admin-check"><input type="checkbox" checked={job.published} onChange={(e) => patchArray("jobs", selectedJob, { published: e.target.checked })}/> Show on jobs page</label><button className="admin-danger" type="button" onClick={() => { removeArray("jobs", selectedJob); setSelectedJob(0); }}>Remove job</button></div>}</div></Panel>}
    {tab === "Testimonials" && <Panel title="Testimonials" eyebrow="FAMILY STORIES"><p className="admin-help">Only use testimonials from people who have approved publication.</p><div className="admin-split"><div className="admin-list">{site.testimonials.map((item, index) => <button className={selectedTestimonial === index ? "selected" : ""} type="button" key={`${item.id}-${index}`} onClick={() => setSelectedTestimonial(index)}>{item.name}</button>)}<button type="button" className="admin-add" onClick={() => { addArray("testimonials", { id: `review-${Date.now()}`, quote: "Add an approved quote.", name: "Name", location: "", published: false } as Testimonial); setSelectedTestimonial(site.testimonials.length); }}>+ Add testimonial</button></div>{testimonial && <div className="admin-detail"><Field label="Name" value={testimonial.name} onChange={(v) => patchArray("testimonials", selectedTestimonial, { name: v })}/><Field label="Location" value={testimonial.location ?? ""} onChange={(v) => patchArray("testimonials", selectedTestimonial, { location: v })}/><Field label="Quote" value={testimonial.quote} onChange={(v) => patchArray("testimonials", selectedTestimonial, { quote: v })} multiline/><label className="admin-check"><input type="checkbox" checked={testimonial.published} onChange={(e) => patchArray("testimonials", selectedTestimonial, { published: e.target.checked })}/> Publish testimonial</label><button className="admin-danger" type="button" onClick={() => { removeArray("testimonials", selectedTestimonial); setSelectedTestimonial(0); }}>Remove testimonial</button></div>}</div></Panel>}
    {tab === "Blog" && <Panel title="Blog & resources" eyebrow="ARTICLES"><div className="admin-split"><div className="admin-list">{site.posts.map((item, index) => <button className={selectedPost === index ? "selected" : ""} type="button" key={`${item.slug}-${index}`} onClick={() => setSelectedPost(index)}>{item.title}</button>)}<button type="button" className="admin-add" onClick={() => { addArray("posts", { slug: `new-post-${Date.now()}`, title: "New Article", excerpt: "Short summary.", body: "Write the article here.", image: site.settings.familyImage, published: false } as Post); setSelectedPost(site.posts.length); }}>+ Add article</button></div>{post && <div className="admin-detail"><Field label="URL slug" value={post.slug} onChange={(v) => patchArray("posts", selectedPost, { slug: v })}/><Field label="Title" value={post.title} onChange={(v) => patchArray("posts", selectedPost, { title: v })}/><Field label="Excerpt" value={post.excerpt} onChange={(v) => patchArray("posts", selectedPost, { excerpt: v })} multiline/><Field label="Article body" value={post.body} onChange={(v) => patchArray("posts", selectedPost, { body: v })} multiline/><Field label="Image URL" value={post.image} onChange={(v) => patchArray("posts", selectedPost, { image: v })}/><label className="admin-check"><input type="checkbox" checked={post.published} onChange={(e) => patchArray("posts", selectedPost, { published: e.target.checked })}/> Publish article</label><button className="admin-danger" type="button" onClick={() => { removeArray("posts", selectedPost); setSelectedPost(0); }}>Remove article</button></div>}</div></Panel>}
    {tab === "Media" && <Panel title="Media library" eyebrow="IMAGE UPLOADS"><p className="admin-help">Upload an image and add alt text. Save or publish after assigning it to a page.</p><form className="admin-upload" onSubmit={upload}><input type="file" name="file" accept="image/*" required disabled={previewOnly}/><input value={mediaAlt} onChange={(e) => setMediaAlt(e.target.value)} placeholder="Describe this image for accessibility" required minLength={3} maxLength={250} disabled={previewOnly}/><button disabled={previewOnly || busy} type="submit">Upload Image</button></form><div className="admin-media-grid">{media.map((item) => <div key={item.id}><img src={item.url} alt={item.alt}/><p>{item.alt}</p><div><button type="button" onClick={() => setSite((current) => ({ ...current, settings: { ...current.settings, heroImage: item.url, heroImageAlt: item.alt } }))}>Use for hero</button><button type="button" onClick={() => setSite((current) => ({ ...current, settings: { ...current.settings, familyImage: item.url, familyImageAlt: item.alt } }))}>Use for family</button><button type="button" onClick={() => setSite((current) => ({ ...current, settings: { ...current.settings, caregiverImage: item.url, caregiverImageAlt: item.alt } }))}>Use for team</button>{service && <button type="button" onClick={() => patchArray("services", selectedService, { image: item.url })}>Use for selected service</button>}{post && <button type="button" onClick={() => patchArray("posts", selectedPost, { image: item.url })}>Use for selected article</button>}</div></div>)}</div>{!media.length && <p className="admin-help">No uploaded images yet. The website currently uses licensed stock photos.</p>}</Panel>}
    {tab === "Inbox" && <Panel title="Submissions inbox" eyebrow="PRIVATE REQUESTS"><p className="admin-help">Select a submission to review its details, reply, or update its status. Showing the 50 most recent of each type.</p><h3>Care inquiries</h3><div className="admin-submissions">{submissionCards("inquiries", inquiries)}</div><h3>Job applications</h3><div className="admin-submissions">{submissionCards("applications", applications)}</div></Panel>}
  </main></div>;
}
