import Link from "next/link";
import type { SiteData } from "@/lib/site-data";

export function SiteFooter({ settings }: { settings: SiteData["settings"] }) {
  return <>
    <section className="footer-cta"><div className="container"><h2>To Get Care Today</h2><p>Call us at <a href={`tel:${settings.phone.replace(/\D/g, "")}`}>{settings.phone}</a></p><Link className="button" href="/contact">Get Care Now</Link></div></section>
    <footer><div className="container footer-grid"><div><Link href="/"><img src="/images/logo-transparent.png" alt={settings.brandName}/></Link><p>{settings.address}</p><nav className="footer-social" aria-label="Social media">{settings.instagramUrl && <a href={settings.instagramUrl} target="_blank" rel="noopener noreferrer" aria-label="Heartstead on Instagram">Instagram ↗</a>}{settings.tiktokUrl && <a href={settings.tiktokUrl} target="_blank" rel="noopener noreferrer" aria-label="Heartstead on TikTok">TikTok ↗</a>}{settings.facebookUrl && <a href={settings.facebookUrl} target="_blank" rel="noopener noreferrer" aria-label="Heartstead on Facebook">Facebook ↗</a>}</nav></div><div><h3>Explore</h3><Link href="/care-services">Our Services</Link><Link href="/service-area">Service Area</Link><Link href="/caregiver-jobs">Caregiver Jobs</Link><Link href="/about-us">About Us</Link></div><div><h3>Get in Touch</h3><Link href="/contact">Contact Us</Link><a href={`tel:${settings.phone.replace(/\D/g, "")}`}>{settings.phone}</a><a href={`mailto:${settings.publicEmail}`}>{settings.publicEmail}</a><Link href="/privacy-policy">Privacy Policy</Link><Link href="/terms-of-service">Terms of Service</Link></div></div><div className="container copyright">© {new Date().getFullYear()} {settings.brandName}. All rights reserved. <span>Photography is illustrative and does not depict Heartstead clients or staff.</span> <Link href="/admin" className="footer-admin">Admin login</Link></div></footer>
  </>;
}
